### ISSUE TITLE
Фильтрация данных по нескольким Id рекламных кампаний

### ISSUE THREAD

**Issue by Apstol** [selesnow/ryandexdirect#1]
Здравствуйте, подскажите, пожалуйста, как отфильтровать данные по нескольким Id кампаний с функцией yadirGetReport, например: FilterList = c("CampaignId IN xxxxxxxx, yyyyyyyy")

**Comment by selesnow** [comment]
Приветствую, вы были правы, оператор IN работал некорректно, эта ошибка исправлена, обновите пакет с помощью приведённого ниже кода:
```r
devtools::install_github("selesnow/rvkstat")
```

После чего вы можете фильтровать кампании через оператор IN, следующим образом:
`FilterList = c("CampaignId IN 13889276 ,19455498","Clicks GREATER_THAN 100")`

При чём разделителем между ID кампаний может быть как запятая, так и точка с запятой и пробел.

Если всё работает корректно можете закрывать тикет.

**Comment by Apstol** [comment]
Спасибо! Все работает.
