### ISSUE TITLE
функция yadirGetClientList(my_token) вызывает сбой аутентификации

### ISSUE THREAD

**Issue by stavrovskaya** [selesnow/ryandexdirect#10]
Добрый день,

Мое приложение использует несколько функций пакета ryadirect. Сегодня обнаружила, функция yadirGetClientList(my_token) вызывает сбой аутентификации, остальные функции при этом работают. Выглядит это так:
![image](https://user-images.githubusercontent.com/19977213/44458417-d2220d00-a60e-11e8-85f3-b2f75a5ffa00.png)
![image](https://user-images.githubusercontent.com/19977213/44458450-fb429d80-a60e-11e8-8e5d-73c7cdd3a76f.png)

**Comment by selesnow** [comment]
получилось загрузить данные? если да то просьба закрыть тикет.

**Comment by stavrovskaya** [comment]
Да, сработало, большое спасибо!
