### ISSUE TITLE
Внесите новые форматы директа, пожалуйста

### ISSUE THREAD

**Issue by grkhr** [selesnow/ryandexdirect#12]
Копался в документации директа и увидел, что в коннекторе не все форматы включены, у которых доступна статистика. CPM_BANNER_CAMPAIGN в кампаниях, а в объявлениях CpcVideoAdBuilderAdFieldNames и CpmBannerAdBuilderAdFieldNames

**Comment by selesnow** [comment]
В РК добавил, в объявлениях фильтра по типу нет, поэтому так и так вытягиваются все типы объявлений которые отдаёт API.
