### ISSUE TITLE
Как установить  скрипт  в msys2

### ISSUE THREAD

**Issue by rdbox** [selesnow/ryandexdirect#13]
не могу понять как мне установить devtools в консоль msys2, разработчики посоветовали к Вам обратиться. Скачивать Rtools не вижу смысла так как у меня уже есть полноценная cygwin консоль только надо как-то до установить нужные пакеты.
Что подскажите ?

**Comment by selesnow** [comment]
Честно говоря никогда ранее даже не слышал о msys2 поэтому ничем помочь не могу в данном случае.
