### ISSUE TITLE
запуск скриптов в linux по расписанию и "Enter authorize code:"

### ISSUE THREAD

**Issue by AutopilotNN** [selesnow/ryandexdirect#14]
Запускаю скрипт R по cron из под debian. Там рядом с файлом скрипта создается <script>.Rout с выводом консоли. Все бы нормально, но при разработке иногда выскакивает запрос "Enter authorize code:". При этом скрипт не останавливается, а файл <script>.Rout разрастается этим сообщением. Большие опасения, что по окончанию срока жизни токена всё свободное место будет исчерпано выводом, и сервер перестанет работать. 
можно ли в yadirAuth.R:
  while(nchar(temp_code) != 7) ...
поставить счетчик попыток с выходом с ошибкой. 

Возможно, в других функциях так же есть readline.   

"R --no-readline" не помогает

**Comment by AutopilotNN** [comment]
yadirAuth.R:
`...
  retry = 3
  while(nchar(temp_code) != 7 & retry > 0)  {
    message("Ïðîâåðî÷íûé êîä ââåä¸ííûé âàìè íå ÿâëÿåòñÿ 7-çíà÷íûì, ïîâòîðèòå ïîïûòêó ââîäà êîäà.")
    temp_code <- readline(prompt = "Enter authorize code:")
    retry = retry - 1 
...`

**Comment by selesnow** [comment]
это сообщение просто так не вылазиет, и скрипт при этом не должен продолжать работу т.к. не пройден процесс авторизации, что то тут не так?

**Comment by AutopilotNN** [comment]
При запуске по линуксовому крону R фактически не дает ничего ввести в readline и выполняет скрипт дальше. поэтому в "while(nchar(temp_code) != 7)" возникает бесконечный цикл. 

Если предположить, что программа на R должна запускаться автоматически, то при пропадании файла с токеном она зависнет, т.к. readline() не работает в не интерактивном режиме - 'In non-interactive use the result is as if the response was RETURN and the value is ""'. 
В консоли linux без оболочки browseURL не работает (файл *.yadirAuth.RData я получил от коллеги с windows машины). 

Да, мой вариант кода неверно работает - возможно, нужно проверять interactive() перед запуском всего куска получения и записи токена и, конечно, делать stop(). Типа: 
```retry = 3
while(nchar(temp_code) != 7) {
    if (retry > 0) { retry = retry - 1 } else { stop("No authorize code") }
....
```

**Comment by selesnow** [comment]
У вас какая то ошибка, и я примерно понимаю в чём она.

Смотрите как проходит процесс авторизации.

### Первое обращение к API через любую функцию rmytarget (кроме функций для метрики, они скоро будут удалены, для метрики надо использовать пакет rym). 

- Сначала функция ищет файл к тором храняться сохранённые при первом обращении к API учётные данные, файл называется Login.yadirAuth.RData, (Ligon тот который вы указали в аргументе Login), если файл найден то всё, учётные данные подтягиваются из него. И программа не доходит вообще до той строки которую вы описали `while(nchar(temp_code) != 7)`.

Вот проверка этого условия `if (NewUser == FALSE && file.exists(paste0(paste0(TokenPath, "/", Login, ".yadirAuth.RData"))))`, строка 11, самое начало [функции](https://github.com/selesnow/ryandexdirect/blob/master/R/yadirAuth.R).

В вашем случае происходит следующее, изначально вы прогнали код в интерактивном режиме, прошли авторизацию, данные сохранились в файл, но вы не используете аргумент `TokenPath`, как раз в нём и надо указать где изначально сохранить файл с учётными данными, и в последствии где функция его должна искать. По умолчанию в `TokenPath` указана текущая рабочая директория.

Так вот видимо в пакетном режиме скрипт запускается с другой рабочей директории.

Что вам надо сделать:

1. Или использовать аргумент `TokenPath`, и указать полный путь к **папке** в которой у вас сохранился файл с учётными данными.

2. Или вначале скрипта сделать её рабочей директорией через setwd().

Убрать цикл ничего не даст, т.к. программа не наход файл с учётными данными, и это вашу проблему не решит.

Подробнее почитайте вот [этот релиз](https://github.com/selesnow/ryandexdirect/releases/tag/3.0.0), я там всё рассписал как работают аргументы `TokenPath`, `Login`, `AgencyAccount`.

**Comment by AutopilotNN** [comment]
Спасибо, но я бы не стал писать сюда по поводу своей проблемы. Ошибку я делал по своей невнимательности, меняя переменные или размещение скрипта. Но мне показалось неправильным как библиотека реагирует на эту ошибку. Т.е. как раз бесконечный цикл. Я узнаю про ошибку по разрастанию файла Rout и по висящему процессу, а это не правильная диагностика.

**Comment by selesnow** [comment]
Ну по логике я рассчитываю на то, что перед кроном и запуском в пакетном режиме скрипт будет отлажен. 

Но за идею вам большое спасибо, я добавил проверку режима работы R, теперь в случае если скрипт не может найти нужный файл для загрузки учётных данных при запуске в пакетном режиме, его работа будет остановлена, и в .Rout будет выводиться следующее сообщение:

`Error in yadirAuth(Login = "mylogin") : 
  Function yadirAuth does not find the mylogin.yadirAuth.RData file in C:/Users/Alsey/Documents. You must run this script in interactive mode in RStudio or RGui and go through the authorization process for create mylogin.yadirAuth.RData file, and using him between R session in batch mode. For more details see realise https://github.com/selesnow/ryandexdirect/releases/tag/3.0.0. For more details about R modes see https://www.r-bloggers.com/batch-processing-vs-interactive-sessions/
Execution halted`.

Думаю это хорошее, и правильное решение вашей проблемы.

Обновите пакет до версии 3.0.12 через: `devtools::install_github("selesnow/ryandexdirect", subdir = "utf8")`.

Если такое решение вам подходит, и ваш скрипт корректно отрабатывает прошу закрывать тикет.

**Comment by AutopilotNN** [comment]
Да, спасибо, все как задумано - при отсутствии файла с токеном выход с сообщением.
