### ISSUE TITLE
В yadirGetAds не возвращается поле SitelinkSetId

### ISSUE THREAD

**Issue by AutopilotNN** [selesnow/ryandexdirect#15]
Без данного поля затруднительно связать наборы быстрых ссылок из yadirGetSiteLinks с объявлениями. 
Можно продублировать часть кода yadirGetAds и самому запросить поле SitelinkSetId. Собственно так и сделал.

**Comment by selesnow** [comment]
Спасибо за инфу, в ближайшие дни добавлю это поле, до конца недели.

**Comment by AutopilotNN** [comment]
В догонку - к сожалению пришлось и дублировать код в yadirGetSiteLinks т.к. в запросе нельзя указать идентификаторы сетов, которые нужно получить, а только логин. У нас в одном клиенте накопилось несколько тысяч быстрых ссылок, принадлежащих архивным кампаниям. Выборка по логину получалась довольно долгая. 

Изначальная задача - написать ревизор ссылок объявлений, чтобы автоматически отслеживать мертвые и ошибочные урлы.

**Comment by selesnow** [comment]
Добрый день, обе просьбы выполнены:

1. Функция `yadirGetAds` теперь возвращает поле *SitelinkSetId*.
2. В функцию `yadirGetSiteLinks` добавлен аргумент *Ids*, который на вход принимает вектор с идентификаторами сетов.

Обновите пакет до версии `3.0.13`:

обновить на Windows: `devtools::install_github("selesnow/ryandexdirect")`
обновить на Linux/Mac: `devtools::install_github("selesnow/ryandexdirect", subdir = "utf8")`

**Спасибо за хорошие предложения по доработке пакетов, и с наступающими вас.**

Если данные доработки соответствуют всему о чём вы писали прошу закрыть тикет.

**Comment by AutopilotNN** [comment]
Спасибо, но в этот раз обновление не прошло. - предупреждения я уже ранее получал, а вот строки 154 в  yadirGetAds.R даже и нет. 
```   ** R
   Предупреждение: не могу перекодировать ‘yadirGetCampaignListOld.R’ строки 4, 11, 19, 32
   Предупреждение: не могу перекодировать ‘yadirGetLogsData.R’ строки 9, 14, 18, 21, 24, 32, 36, 39, 41, 44, 47, 58, 61, 64, 77, 82, 84, 87, 89
   Предупреждение: не могу перекодировать ‘yadirGetReport.R’ строку 149
   Предупреждение: не могу перекодировать ‘yadirGetSummaryStat.R’ строки 8, 12, 16, 19, 27, 30
   Error in parse(outFile) :
     /tmp/Rtmpl160fP/Rbuild45bd4ab2aef6/ryandexdirect/R/yadirGetAds.R:154:45: неожиданный ','
   153:   return(result)}
   154: ftime(stop_time, start_time , units ="secs"),
                                                    ^
   ERROR: unable to collate and parse R files for package ‘ryandexdirect’
─  removing ‘/tmp/Rtmpl160fP/Rinst45bd714bd2b7/ryandexdirect’
         -----------------------------------
   ERROR: package installation failed
Ошибка в run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  :
  System command error
```

**Comment by AutopilotNN** [comment]
Концовка этого файла явно имеет ошибку - два return(result)}

ryandexdirect-master\utf8\R\yadirGetAds.R
```
  # tech messages
  packageStartupMessage("Done", appendLF = T)
  packageStartupMessage(paste0("Number of load ads: ", nrow(result)), appendLF = T)
  packageStartupMessage(paste0("Duration: ", round(difftime(stop_time, start_time , units ="secs"),0), " sec."), appendLF = T)
  # return of result
  return(result)}
ftime(stop_time, start_time , units ="secs"),0), " сек."), appendLF = T)
#Возвращаем результат
return(result)}
```

**Comment by AutopilotNN** [comment]
А теперь я понимаю откуда ошибки в кодировке - у перечисленных файлов cp1251 перекодировано 2 раза.

**Comment by selesnow** [comment]
Пробуйте, я перезалил версию для linux и исправил ошибку которая изза перекодировки вылезла.

**Comment by AutopilotNN** [comment]
yadirGetSiteLinks.R:67:1: неожиданный ')'
   66: }
   67: )
       ^

**Comment by AutopilotNN** [comment]
Кодировки коментов поломаны в файлах:
yadirCurrencyRates.R
yadirGetCampaignListOld.R
yadirGetClientParam.R
yadirGetLogsData.R
yadirGetSummaryStat.R
```
    #If logins more than 100 run cicle by 100 logins
    #Г‚ Г±Г«ГіГ·Г ГҐ ГҐГ±Г«ГЁ ГўГўГҐГ¤ГҐГ­Г® ГЎГ®Г«ГҐГҐ 100 Г«Г®ГЈГЁГ­Г®Гў Г­ГҐГ®ГµГ®Г¤ГЁГ¬Г® Г®ГЎГ®Г©ГІГЁ Г®ГЈГ°Г Г­ГЁГ·ГҐГ­ГЁГҐ API ГЁ Г®ГІГЇГ°Г ГўГ«ГїГІГј Г§Г ГЇГ°Г®Г±Г» Г®ГІГ¤ГҐГ«ГјГ­Г® ГЇГ® 100 Г«Г®ГЈГЁГ­Г®Гў
```

**Comment by AutopilotNN** [comment]
Извиняюсь, промахнулся и закрыл issue. 
В конце файла yadirGetSiteLinks.R так же дублирующиеся строки. 
Ощущение, что происходит ошибка с накладыванием патчей на исходники.

**Comment by selesnow** [comment]
Это у меня при пакетной перекодировки в UTF-8 что то видимо слетело, перезалил, пробуйте.

**Comment by AutopilotNN** [comment]
не исправлен yadirGetSiteLinks.R ошибка. Выше я писал про него. код после "return(result)}" лишний
```
  # result
  return(result)
}
)) {
      offset <- offset + limit
    } else {
      break
      }
  }
  
  # возвращаем полученный массив
  return(result)
}
```

**Comment by selesnow** [comment]
Извиняюсь, путаница из-за двух параллельных версий, я сам вообще не использую версию для linux, она мне не нужна и тестировать её не на чем.
Пробуйте.

**Comment by AutopilotNN** [comment]
Спасибо, версия скомпилировалась, но в yadirGetCampaignList.R стала кодировка cp1251.  
Не читаем вывод сообщений: 
packageStartupMessage(paste0("Количество полученных рекламных кампаний: ", nrow(result)), appendLF = T)
packageStartupMessage(paste0("Длительность работы: ", round(difftime(stop_time, start_time , units ="secs"),0), " сек."), appendLF = T)

Думаю, стоит на сегодня остановиться ))) Спасибо за правки. Желаю удачного нового года.

**Comment by AutopilotNN** [comment]
После праздников проверю кодировку и вышлю что не так.

**Comment by selesnow** [comment]
Вроде в utf-8, т.к. github превращает кириллицу в 1251 в кракозябры, а в этой функции вроде всё ок
http://img.netpeak.ua/alsey/154610122478_kiss_41kb.png

**Comment by selesnow** [comment]
Да и в целом я готовлю ryandexdirect к публикации на CRAN, поэтому в январе я от туда всю кириллицу уберу, сообщения будут на англ, CRAN по другому не пускает.

**Comment by AutopilotNN** [comment]
В файлах ниже в комментариях встречаются некорректные для UTF-8 символы. Компилятор не может обработать такие строки.   

yadirCurrencyRates.R:18
yadirGetCampaignListOld.R:4
yadirGetCampaignListOld.R:8
yadirGetCampaignListOld.R:11
yadirGetCampaignListOld.R:15
yadirGetCampaignListOld.R:19
yadirGetCampaignListOld.R:32
yadirGetCampaignListOld.R:44
yadirGetCampaignListOld.R:45
yadirGetCampaignListOld.R:57
yadirGetCampaignListOld.R:63
yadirGetClientParam.R:44
yadirGetClientParam.R:46
yadirGetClientParam.R:56
yadirGetClientParam.R:58
yadirGetClientParam.R:79
yadirGetClientParam.R:80
yadirGetLogsData.R
yadirGetSummaryStat.R

В двух последних файлах комментариев оч много.

**Comment by selesnow** [comment]
Сегодня исправил все проблемы с кодировками и некорректиными символами, можете переустановить пакет.
