### ISSUE TITLE
Некорректный запрос - В HTTP-заголовке Client-Login необходимо указать логин рекламодателя

### ISSUE THREAD

**Issue by vladik86** [selesnow/ryandexdirect#16]
Как бороться и в чём проблема?
![image](https://user-images.githubusercontent.com/31451963/50967172-2b74d500-14f9-11e9-92fc-734e7bf0da7d.png)

**Comment by selesnow** [comment]
Видимо вы указали в аргумерт Logins - логин управляющего, агентского аккаунта, но его надо указывать в аргументе AgencyAccount, а в аргумент Logins надо передавать логин клинтского аккаунта.

**Comment by selesnow** [comment]
Подскажите получилось решить вашу проблему? 
Если да то прошу закрыть тикет.

**Comment by vladik86** [comment]
Благодарю, разобрался.
