### ISSUE TITLE
При подключении к PowerBi выдает ошибку ADO.NET: R script error

### ISSUE THREAD

**Issue by Casper969** [selesnow/ryandexdirect#17]
Привет!

Хочу поблагодарить Вас за проделанную работу!

У меня есть проблема, которую не могу решить уже несколько дней.

Провожу настройку вот по этой инструкции https://netpeak.net/ru/blog/kak-svyazat-yandeks-direkt-s-microsoft-power-bi/

Подошел к шагу связки с Power Bi и выдается одна и та же ошибка

`Welcome to ryandexdirect version 3.0.13.0

Author:   Alexey Seleznev (Head of analytics dept at Netpeak).
Email:    selesnow@gmail.com
Blog:     https://alexeyseleznev.wordpress.com 
Facebook: https://facebook.com/selesnown 
Linkedin: https://www.linkedin.com/in/selesnow 

Type ?ryandexdirect for the main documentation.
The github page is: https://github.com/selesnow/ryandexdirect/

Suggestions and bug-reports can be submitted at: https://github.com/selesnow/ryandexdirect/issues
Or contact: <selesnow@gmail.com>

	To suppress this message use:  suppressPackageStartupMessages(library(ryandexdirect))
---------------------

Ошибка в yadirGetCampaignList(logins = "avto*****", token = "AQAAAAAS-******************************") :
  неиспользованные аргументы (logins = "avtoforumkia", token = "AQAAAAAS-********************************")
Выполнение остановлено
`

Подскажите как решить данную проблему? И с чем она может быть связана?

**Comment by selesnow** [comment]
Обсуждение было на Facebook, доступно по [ссылке](https://www.facebook.com/groups/1385177031811951?view=permalink&id=1990876954575286), может там найдёте ответ.
