### ISSUE TITLE
Добавьте пожалуйста в yadirGetCampaignList поле BiddingStrategy

### ISSUE THREAD

**Issue by Aztekk** [selesnow/ryandexdirect#18]
Оно находится внутри полей 
TextCampaign
DynamicTextCampaign
MobileAppCampaign
CpmBannerCampaig

**Comment by VadimPlasiciuc** [comment]
@Aztekk 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by selesnow** [comment]
Добрый день, взял в работу, будет в ближайшем релизе вместе с публикацией пакета на cran.

Вам отпишусь тут, и обязательно опубликую новость в [канале](https://t.me/R4marketing).

**Comment by selesnow** [comment]
Ещё раз спасибо за предложение и ожидание, данный функционал добавлен в пакет в версию 3.1.5.

Обновить пакет уже можно из CRAN: `install.packages("ryandexdirect")`
