### ISSUE TITLE
Получение данных о доходах и расходах

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/ryandexdirect#2]
Здравствуйте, возможно ли выгружать такую же статистику которую мы получаем в разделе Директ.Расходы в интерфейсе метрики. Т.е что бы были видны рекламные кампании в разрезе объявлений с расходами, визитами, доходам и количеством заказов?

**Comment by Wreitlein** [comment]
Я пытаюсь с помощью 
`library(ryandexdirect)
rawmetrikdata <- yadirGetLogsData(counter = "****",
                                  date_from = "2018-01-01",
                                  date_to = "2018-03-20",
                                  fields = "ym:s:date,ym:s:lastsignDirectClickBanner,ym:s:bounce,ym:s:networkType,ym:s:purchaseRevenue,ym:s:ecommercePurchases",
                                  source = "visits",
                                  token = "****")`
Но на попытки забрать хотя бы заголовок (ym:s:lastsignDirectClickBanner) получаю ошибку Unknown field ym:s:lastsignDirectClickBanner, error code - 400

**Comment by selesnow** [comment]
Добрый день, дело в том, что поля `ym:s:lastsignDirectClickBanner` в самом деле нет в [справочнике](https://tech.yandex.ru/metrika/doc/api2/logs/fields/visits-docpage/), попробуйте вместо него использовать поле `ym:s:openstatAd` или `ym:s:lastDirectClickBanner`.

**Comment by Wreitlein** [comment]
Спасибо, помогло, но видимо данная библиотека не совсем подходит для этой задачи.

**Comment by selesnow** [comment]
В ближайших планах у меня есть разработка отдельной расширенной библиотеки для работы с Яндекс Метрикой, там в любом случае будет возможность получить любой отчёт из Метрики.

**Comment by Wreitlein** [comment]
Было бы замечательно, если бы в нём была возможность совмещать данные о доходах (заказах) из метрики с расходами из метрики для того, чтобы можно было соединять эти данные в одну таблицу. Например по id креатива.
