### ISSUE TITLE
Реализовать поддержку новой системы авторизации API Яндекс.Метрики

### ISSUE THREAD

**Issue by alt344** [selesnow/ryandexdirect#20]
"Передача авторизационного токена в параметрах URL перестанет работать 13 февраля 2019 года. Чтобы продолжить работу с API Метрики, настройте авторизацию по токену в HTTP-заголовке."
на всех страницах методов в мануале https://tech.yandex.ru/metrika/doc/api2/management/intro-docpage/.

Соответственно не работает yadirGetLogsData при наличии описанной в документации ryandexdirect схемы с токеном. Возвращает ошибку "unauthorized - Неавторизованный пользователь, error code - 401"

**Comment by mrykin** [comment]
Используйте пакет https://github.com/selesnow/rym для работы с Метрикой.

**Comment by selesnow** [comment]
Здравствуйте, Павел совершенно верно написал, я ещё в декабре сообщил о том, что из пакета ryandexdirect будут перенесены функции для работы с метрикой в пакет rym.
