### ISSUE TITLE
Ошибка установки cp: unknown option--

### ISSUE THREAD

**Issue by KoalaDotOvermind** [selesnow/ryandexdirect#21]
install_github('selesnow/ryandexdirect')
Downloading GitHub repo selesnow/ryandexdirect@master
√  checking for file 'D:\Temp\RtmpekrS4f\remotes137419bd1606\selesnow-ryandexdirect-af890f5/DESCRIPTION' ... 
-  preparing 'tidyr':
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
         -----------------------------------
-  installing *binary* package 'tidyr' ...
   cp: unknown option -- )
   Try '/rtools35/bin/cp --help' for more information.
   ERROR: installing binary package failed
-  removing 'D:/Temp/RtmpOiUzdp/Rinst285842fa40ea/tidyr'
   In R CMD INSTALL
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

> find_rtools(T)
Scanning R CMD config CC...
cc_path: D:/Programs/rtools35/mingw_64/bin/gcc 
install_path: D:/Programs/rtools35 
VERSION.txt
Rtools version 3.5.0.4 
Found compatible gcc from R CMD config CC
[1] TRUE

**Comment by selesnow** [comment]
Здравствуйте, в самом деле был битый файл DESCRIPTION, ошибку уже исправил, попробуйте ещё раз установить пакет.

**Comment by KoalaDotOvermind** [comment]
Установка заработала. Спасибо
