### ISSUE TITLE
Прогноз бюджета / показов

### ISSUE THREAD

**Issue by DemureLess** [selesnow/ryandexdirect#26]
Алексей добрый день.
Не смог найти в пакете, и поэтому предлагаю реализовать, прогноз бюджетов

**Comment by selesnow** [comment]
Беру в работу, спасибо за предложение, извиняюсь что так долго добирался до вашего тикета.

**Comment by selesnow** [comment]
Добавил функцию для загрузки бюджета

```
forecast <- yadirGetForecast(c('купить смартфон -xiaomi', 'купить xiaomi'),
                             Login = "selesnow")
```

Так же теперь есть функция для работы с Word Stat
```
minus_ws_rep <- yadirGetWordStatReport(c('купить смартфон -xiaomi', 'самсунг'),
                                       Login = "selesnow")
```
