### ISSUE TITLE
Превышено допустимое количество идентификаторов в массиве SelectionCriteria.CampaignIds при вызове yadirGetKeyWords

### ISSUE THREAD

**Issue by gitmexanism** [selesnow/ryandexdirect#27]
Добрый день, Алексей.

Выполняю код:

    library(ryandexdirect)
    
    # Авторизация 
    yadirAuth(Login     = "login",
              TokenPath = "C:/direct/tokens")

    # Список рекламных кампаний
    camp <- yadirGetCampaignList(Logins    = "login",
                                 TokenPath = "C:/direct/tokens")
        
    # Список ключевых слов
    kw <- yadirGetKeyWords(Login       = "login",
                           TokenPath   = "C:/direct/tokens",
                           CampaignIds = camp$Id,
                           WithStats   = F)
    
    # Загрузка баланса аккаунта
    balance <- yadirGetBalance(Logins  = "login",
                               TokenPath   = "C:/direct/tokens")

Выдаёт ошибку:

Ошибка в yadirGetKeyWords(Login = "login", TokenPath = "C:/direct/tokens",  :
Неверно заданы параметры фильтрации SelectionCriteria - Превышено допустимое количество идентификаторов в массиве SelectionCriteria.CampaignIds

В сообщениях встречал подобную ошибку для функции yadirGetBalance, 
где SelectionCriteria.Logins содержал более 50 элементов. 
Здесь (https://github.com/selesnow/ryandexdirect/issues/4#issuecomment-385940325)

Как я понимаю, у меня то же самое, только для SelectionCriteria.CampaignIds в функции yadirGetKeyWords.

**Comment by selesnow** [comment]
Какая у вас версия пакета, скорее всего вам достаточно было просто его оновить?

**Comment by gitmexanism** [comment]
Решил проблему добавив фильтрацию после получения рекламных кампаний

```
# Список рекламных кампаний (Обязателен при получении других объектов)
campAll <- yadirGetCampaign(Login    = "login",
                            AgencyAccount = "acc",
                            TokenPath = "C:/path/tokens")
    
camp <- campAll[campAll$Clicks > 0, ]
    
# Список ключевых слов
kw <- yadirGetKeyWords(Login = "login",
                       AgencyAccount = "acc",
                       TokenPath = "C:/path/tokens",
                       CampaignIds = camp$Id,
                       WithStats = F)
```
До какого-то времени это работало, то сегодня снова появилась ошибка

`Неверно заданы параметры фильтрации SelectionCriteria - Превышено допустимое количество идентификаторов в массиве SelectionCriteria.CampaignIds`

Выходит что попадаю на ограничение по количеству выгружаемых фраз...
Пока не придумал как обойти.

**Comment by gitmexanism** [comment]
@selesnow, версия пакета 
Решил проблему добавив фильтрацию после получения рекламных кампаний

# Список рекламных кампаний (Обязателен при получении других объектов)
campAll <- yadirGetCampaign(Login    = "login",
                            AgencyAccount = "acc",
                            TokenPath = "C:/path/tokens")
    
camp <- campAll[campAll$Clicks > 0, ]
    
# Список ключевых слов
kw <- yadirGetKeyWords(Login = "login",
                       AgencyAccount = "acc",
                       TokenPath = "C:/path/tokens",
                       CampaignIds = camp$Id,
                       WithStats = F)
До какого-то времени это работало, то сегодня снова появилась ошибка

Неверно заданы параметры фильтрации SelectionCriteria - Превышено допустимое количество идентификаторов в массиве SelectionCriteria.CampaignIds

Выходит что попадаю на ограничение по количеству выгружаемых фраз...
Пока не придумал как обойти.

**Comment by gitmexanism** [comment]
Пока придумал только разделить список кампаний по State (ARCHIVED, SUSPENDED, ON), получить фразы для каждого списка кампаний, а затем склеить:

При получении списка ключевых фраз для архивных кампаний возвращается 0 фраз, поэтому фильтрацию архивных кампаний убрал.

В итоге получилось так:

# получаем все кампании логина
campAll <- yadirGetCampaign(Login    = "login",
                                                  AgencyAccount = "acc",
                                                  TokenPath = "C:/path/tokens")

# фильтруем, оставляя только кампании с кликами
camp <- campAll[campAll$Clicks > 0,]

#выделяем запущенные кампании
camp_ON <- camp[camp$State == "ON",]

#выделяем остановленные кампании
camp_SUSPENDED <- camp[camp$State == "SUSPENDED",]

# Получаем список ключевых фраз для запущенных кампаний
kw_ON <- yadirGetKeyWords(Login = "login",
                                                AgencyAccount = "acc",
                                                TokenPath = "C:/path/tokens",
                                                CampaignIds = camp_ON$Id,
                                                WithStats = F)

# Получаем список ключевых фраз для остановленных кампаний
kw_SUSPENDED <- yadirGetKeyWords(Login = "login",
                                                               AgencyAccount = "acc",
                                                               TokenPath = "C:/path/tokens",
                                                               CampaignIds = camp_SUSPENDED$Id,
                                                               WithStats = F)

#Склеиваем
kw <- rbind(kw_ON, kw_SUSPENDED)
