### ISSUE TITLE
Ошибка в функции yadirGetKeyWordsBids

### ISSUE THREAD

**Issue by sergeymong** [selesnow/ryandexdirect#28]
Получаю ставки ключевых слов с помощью функции `yadirGetKeyWordsBids`.
Вызываю как в примерах:
```
bids  <- yadirGetKeyWordsBids(
    KeywordIds = kw$Id, 
    AuctionBids = 'search',
    Login = account_login, 
    TokenPath = token_path
  )
```

В kw — результаты `yadirGetKeyWords` по одной из кампаний. Id — идентификаторы ключевых слов.

На части ключевых слов функция отрабаывает хорошо, но вот на части ключевых слов происходит ошибка, причём независимо от того, какая длина вектора передаётся в `yadirGetKeyWordsBids` (1, 3, 10, 1000). Traceback ошибки:
```
 Error: Argument 5 is a list, must contain atomic vectors 
4.
stop(structure(list(message = "Argument 5 is a list, must contain atomic vectors", 
    call = NULL, cppstack = NULL), class = c("Rcpp::exception", 
"C++Error", "error", "condition"))) 
3.
bind_rows_(x, .id) 
2.
dplyr::bind_rows(res_flatting) 
1.
yadirGetKeyWordsBids(KeywordIds = c(16556358703), AuctionBids = "search", 
    Login = account_login, TokenPath = token_path) 
```
Посмотрев код, я так понял, ошибка возникает в самом конце при приведении результатов к плоскому виду.

**Comment by selesnow** [comment]
Добрый день. Спасибо за информацию.

Да, судя по всему функция не может собрать полученные результаты в таблицу, что бы окончательно разобраться с проблемой мне необходимо у себя воспроизвести ошибку. 

Постараюсь на неделе добраться до этого.

**Comment by selesnow** [comment]
Добрый день, ошибка исправлена, установите пакет из GitHub и функция будет работать.

`devtools::install_github('selesnow/ryandexdirect')`
