### ISSUE TITLE
Ошибка в функции yadirGetReport

### ISSUE THREAD

**Issue by rgobov** [selesnow/ryandexdirect#29]
на запрос 
stat <- yadirGetReport(DateFrom = 2020-03-03,
                                DateTo = 2020-03-14,
                                FieldNames    = c("Date", "Clicks", "Impressions"),
                                AgencyAccount         = "#######",
                                TokenPath     = "metrica_token")
Выскакивает ошибка: Error in paste0(round(as.integer(server_time)/as.integer(total_work_time) *  : 
  object 'server_time' not found

**Comment by selesnow** [comment]
Так вы же не указали из какого аккаунта хотите получить данные, используйте аргумент `Logons`.
