### ISSUE TITLE
Статистика в разрезе групп / слов

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/ryandexdirect#3]
Здравствуйте, возможно ли с помощью yadirGetSummaryStat получить данные в разрезе групп объявлений и ключевых слов?

**Comment by selesnow** [comment]
Добрый день, `yadirGetSummaryStat` можно считать устаревшей функцией, я её разработал ещё до того как появился [сервис Reports](https://tech.yandex.ru/direct/doc/reports/reports-docpage/), на данный момент наиболее удобной и гибкой функцией для получения статистики в разрезе рекламных кампаний, групп объявлений, ключевых слов и объявлений является функция `yadirGetReport`.

Подробное описание и примеры кода для работы с этой функцией вы найдёте в статье "[Что такое язык R и как работать с API рекламных систем Google AdWords и Яндекс.Директ с его помощью](https://www.owox.ru/blog/articles/r-language-and-api-of-ad-systems/)"

**Comment by Wreitlein** [comment]
Понял, спасибо.
