### ISSUE TITLE
Ошибка при выполнении SEARCH_QUERY_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by JuliaDoshlova** [selesnow/ryandexdirect#30]
Добрый день, Алексей!
Выполняю запрос SEARCH_QUERY_PERFORMANCE_REPORT за небольшой период в 10 дней. Какие-то периоды обрабатываются нормально, а в какие-то выходит ошибка. Не могу понять из-за чего.

Вот такой запрос:
![image](https://user-images.githubusercontent.com/5521719/77734464-cc29b480-7019-11ea-9cf1-e761e1da197e.png)

Далее появляется ошибка с таким результатом:
-----------------------------------------------------------
Warning message:
In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)

Привожу скриншот ошибки:
![image](https://user-images.githubusercontent.com/5521719/77735359-79e99300-701b-11ea-8a4e-2106afee05ef.png)

В итоговый файл происходит неполное сохранение полученных данных. 
Выгружаю в csv, данные должны разбиваться по столбам. Но видимо после ошибки в какой-то момент они все слепливаются в одну строку без разделителя. Привожу скриншот ниже:

![image](https://user-images.githubusercontent.com/5521719/77739002-dcde2880-7021-11ea-9422-ab461586a67f.png)

Есть предположение, что какая-то ошибка выходит при обработке нулевых значений.
Но пока я не поняла как поправить. Алексей, буду вам очень благодарна за помощь. 

**_С уважением, Дошлова Юлия
e-mail: u.doshlova@gmail.com_**

**Comment by JuliaDoshlova** [comment]
Кажется поняла, в чем дело. В одном из запросов встречается слэш и после этого скрипт выдает ошибку. Ругается на 2755 строку.
Не знаю как перевести здесь на русский язык, но ясно, что ошибка в 2755 строке:
2755 Query           delimiter or quote

![image](https://user-images.githubusercontent.com/5521719/77739134-1151e480-7022-11ea-9481-4c24da3ab680.png)


А в этой строке как раз впервые встретился слэш:
в csv строка 2756, так как еще есть строка заголовков:
![image](https://user-images.githubusercontent.com/5521719/77739002-dcde2880-7021-11ea-9422-ab461586a67f.png)

Как поправить - всё равно пока не знаю...

**Comment by selesnow** [comment]
Добрый день, дело в том что для R `\` это спец символ, который обозначает экранирование, подумаю над тем как решить.

Но, судя по тому что у вас все сообщения в битой кирилице у вас какая то очень старая версия пакета, скорее всего вам достаточно будет просто переустановить пакет из CRAN, и ошибка сама уйдёт.

 `install.packages('ryandexdirect')`

**Comment by JuliaDoshlova** [comment]
Алексей, добрый день!
Пакет переустановила, надписи в кириллице ушли. Благодарю!
Но проблема с выгрузкой тем не менее осталась. 

Опять пишет ошибку на строке со слэшем, строка 2755:
![image](https://user-images.githubusercontent.com/5521719/78972498-922ad900-7b16-11ea-8e75-0bd3b04465b3.png)

А в выгрузке в csv выгружает все данные, но после слэша перестает бить их по столбцам:
![image](https://user-images.githubusercontent.com/5521719/78972565-bb4b6980-7b16-11ea-9124-1a2c0d061445.png)

**Comment by selesnow** [comment]
Единственное, что могу посоветовать не использовать в названии кампании зарезервированные спец символы, это в принципе не правильно, используйте прямой слеш например, решётку, или ещё что - то, но не обратный слеш.
