### ISSUE TITLE
Ошибка при выполнении функции yadirGetKeyWordsBids

### ISSUE THREAD

**Issue by vitovladimirov** [selesnow/ryandexdirect#32]
Всем привет. 
При выполнении функции yadirGetKeyWordsBids возникает ошибка "Ошибка: Argument 5 is a list, must contain atomic vectors"
Код ниже прилагаю. Пакет переустанавливал. Кто нибудь знает, как победить проблему?
Как я понял, аргумент 5 у этой функции это Login, но в других функциях все исправно работает без ошибок.

`
library(ryandexdirect)

YaLogin = "zzclickdirect-agent-172024"
YaTokenPath = "C:/Users/79165/Documents/R/direct_tokens_всекулеры"
ObjectStates = c("ON","OFF")

#1 Авторизируемся в Яндекс.Директ и получаем токен
Auth = yadirAuth(Login = YaLogin, NewUser = TRUE, TokenPath = YaTokenPath)

#2 Получаем статистику по ключам
Report = yadirGetReport(ReportType = "CUSTOM_REPORT", 
                        DateRangeType = "LAST_MONTH", 
                        DateFrom = NULL, 
                        DateTo = NULL, 
                        FieldNames = c("CampaignName","Impressions","Clicks","Cost","CampaignId","CriteriaId","CriteriaType"), 
                        FilterList = NULL, 
                        IncludeVAT = "NO", 
                        IncludeDiscount = "NO", 
                        Login = YaLogin, 
                        TokenPath = YaTokenPath)

get_kw <- yadirGetKeyWords(CampaignIds = Report$CampaignId, 
                           States = ObjectStates, 
                           Login = YaLogin, 
                           TokenPath = YaTokenPath)

get_kw_bids = yadirGetKeyWordsBids(KeywordIds = get_kw$Id,
                                   TokenPath = YaTokenPath,
                                   Login = YaLogin)`

**Comment by selesnow** [comment]
Скорее всего про 5 аргумент, это не в функции `yadirGetKeyWordsBids()`, а в какой то из функций которая под капотом используется, могли бы вы дать полный вывод ошибки в консоль?

И возможно проблема уже решилась в более новых версиях пакета?
