### ISSUE TITLE
История запросов

### ISSUE THREAD

**Issue by Pirshtuk** [selesnow/ryandexdirect#36]
Как получить в R таблицу с [историей запросов по периодам](https://wordstat.yandex.com/#!/history).

**Comment by selesnow** [comment]
По большому счёту никак, метода для запроса таких данных в API Яндекс Директ нет.

Как вариант пишите парсер вордстата с использованием  пакета rvest, но это не совсем "легальный" способ получения таких данных, а "легального" увы не существует.
