### ISSUE TITLE
Ошибка при работе с агентским аккаунтом

### ISSUE THREAD

**Issue by energystuff** [selesnow/ryandexdirect#4]
Выполняю Ваш код для агентского аккаунта:

library(ryandexdirect)
myToken <- yadirGetToken()
clientList <- yadirGetClientList(myToken)
campaignList <- yadirGetCampaignList(logins = clientList$Login, token = myToken)
stat <- yadirGetSummaryStat(campaignIDS = campaignList$Id,
                            dateStart = "2016-01-01",
                            dateEnd = "2016-06-30",
                            currency = "USD",
                            token = myToken)

======
Ошибка в dataRaw$data[[i]][c("FIO", "Login", "DateCreate", "Phone", "Email",  :
  неправильный тип подгруппы 'list'
Вызовы: yadirGetClientList
Выполнение остановлено
"
=======
Подскажите, как исправить?

**Comment by selesnow** [comment]
Добрый день, подскажите а какая у вас установлена версия ryandexdirect? проверить это можно командой `utils::packageDescription("ryandexdirect")$Version`. Возможно ошибка вызвана тем, что у вас старая версия пакета.

Далее ошибка в названии аргументов в функции `yadirGetCampaignList`, после [обновления](https://github.com/selesnow/ryandexdirect/releases/tag/2.4.4), которое было пару месяцев назад аргументы необходимо именовать с заглавной буквы, т.е. не logins и token, а Logins и Token.

И ещё я вам не рекомендую использовать функцию `yadirGetSummaryStat`, она была написана до того как в 5 версии API появился Report Service, сейчас намного более гибкие возможности для запроса статистики даёт функция [yadirGetReport](https://selesnow.github.io/ryandexdirect/#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B5%D0%B9-yadirgetreport-%D0%B8-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8%D0%B7-%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%B0-reports)

Пример кода для работы с ней:
```r
library(ryandexdirect)
myToken <- yadirGetToken()
My_report <- yadirGetReport(ReportType = "CAMPAIGN_PERFORMANCE_REPORT", 
                            DateRangeType = "CUSTOM_DATE", 
                            DateFrom = '2017-01-01', 
                            DateTo = '2017-01-31', 
                            FieldNames = c("CampaignName","Impressions","Clicks"), 
                            FilterList = c("Clicks GREATER_THAN 49","Impressions LESS_THAN 1001"), 
                            Login = <YourLogin>, 
                            Token = myToken)
```

Пока попробуйте обновить пакет, наверняка у вас старая версия - `devtools::install_github('selesnow/ryandexdirect')`.

**Comment by energystuff** [comment]
Спасибо, заработало, а какой синтаксис для указания нескольких аккаунтов? Необходимо в рамках одного проекта Power BI видеть статистику для нескольких клиентов.

**Comment by energystuff** [comment]
Спасибо! Работает. Вопрос касательно получения баланса:
Получаю баланс с помощью кода:
my_clients_balance <- yadirGetBalance(Logins = clientList$Login,  Token = "***")

Ошибка в yadirGetBalance(Logins = clientList$Login, Token = "***") :
  Error: code - 241, message - Превышен допустимый размер массива, detail - Массив SelectionCriteria.Logins должен содержать не более 50 элементов
Выполнение остановлено
"

Как решить данную проблему?

**Comment by selesnow** [comment]
Добрый день.

> 1. Error: code - 241, message - Превышен допустимый размер массива, detail - Массив SelectionCriteria.Logins должен содержать не более 50 элементов

Доработал функцию yadirGetBalance, теперь можно запрашивать данные более чем по 50 аккаунтам, для того что бы изменения вступили в силу у вас переустановите пакет с помощью команды `devtools::install_github("selesnow/ryandexdirect")`

> Как не учитывать аккаунты в архиве? Уходит много времени на загрузку данных по ним.

Вы можете отфильтровать полученную таблицу клиентов, смотрите пример кода:

```r
# подключаем пакет
library(ryandexdirect)
# получаем токен
yatoken <- yadirGetToken()
# получаем список клиентов из агентского аккаунта
clients <- yadirGetClientList(yatoken)
# оставляем только активных клиентов
active_cllients <- clients[clients$StatusArch == "No", ]
# запрашиваем остатки баланса по активным клиентам
client_balance <- yadirGetBalance(Logins = active_cllients$Login, yatoken)
```

**Comment by selesnow** [comment]
Подскажите получилось решить вашу проблему, если да прошу закрыть тикет.
