### ISSUE TITLE
Не работает пакет на версии R 3.5.0

### ISSUE THREAD

**Issue by zkostitsyn** [selesnow/ryandexdirect#5]
При установке пакета выдаёт ошибку о невозможности установки в связи с версией R 3.5.0

**Comment by selesnow** [comment]
Я только что залил [очень большое обновление](https://github.com/selesnow/ryandexdirect/releases/tag/3.0.0), попробуй заново переустановить пакет.

**Comment by selesnow** [comment]
Проблема была решена?

**Comment by zkostitsyn** [comment]
Да, спасибо
