### ISSUE TITLE
При запуске из Power BI не коннектится к R

### ISSUE THREAD

**Issue by bruiko** [selesnow/ryandexdirect#7]
При запуске скрипта из Power BI перенаправляет на страницу с авторизационным кодом (хотя ранее через RStudio авторизационные данные были получены и сохранены в папку token_yandex). В результате Power BI выдает окно Connection (Please wait while we establish a connection to R), скрин во вложении.
![power bi - mistake](https://user-images.githubusercontent.com/40170402/41231366-8be32a56-6d8b-11e8-9732-bc7a12b5075b.JPG)

**Comment by antonrybin** [comment]
Похожая проблема когд получаю баланс на агентском аккаунте. Написал скрипт, при запуске из Rstudio все работает. При сохранении скрипта и запуске по расписанию в логах пишет следующее:

clients <- yadirGetClientList(AgencyAccount = "*********", TokenPath = getwd())
Error in shell.exec(url) : 
  file association for 'https://oauth.yandex.ru/authorize?response_type=code&client_id=***********************&redirect_uri=https://selesnow.github.io/ryandexdirect/getToken/get_code.html&force_confirm=0&login_hint=**********' not available or invalid
Calls: yadirGetClientList -> tech_auth -> yadirAuth -> browseURL -> shell.exec
Execution halted

звездочками заменил агентский логин и id

**Comment by selesnow** [comment]
> Похожая проблема когда получаю баланс на агентском аккаунте. Написал скрипт, при запуске из Rstudio все работает. При сохранении скрипта и запуске по расписанию в логах пишет следующее:

clients <- yadirGetClientList(AgencyAccount = "", TokenPath = getwd())
Error in shell.exec(url) :
file association for 'https://oauth.yandex.ru/authorize?response_type=code&client_id=***********************&redirect_uri=https://selesnow.github.io/ryandexdirect/getToken/get_code.html&force_confirm=0&login_hint=*' not available or invalid
Calls: yadirGetClientList -> tech_auth -> yadirAuth -> browseURL -> shell.exec
Execution halted

звездочками заменил агентский логин и id

Передавайте в аргумент TokenPath полный путь, например 'c:/my_r_script/' (т.к. при запуске из RStudio рабочей папкой является "мои документы", при запуске из Power BI другая директория), далее один раз прогоните скрипт именно из RStudio, т.к. в RStuio R запускается в интерактивном режиме, получите и сохраните токен, т.к. Power BI запускает R в пакетном режима, а пакетный режим не даёт возможности запуска браузера, и получить токен запустив скрипт из Power BI не получится, т.к. при запуске из RStudio рабочей папкой является "мои документы", при запуске из Power BI другая директория.

После чего токен сохранится в указанную в аргументе TokenPath папку, и при запуске скрипта из Power BI будет подтягивать учётные данные именно из файла, запускать браузер больше не понадобится.

**Comment by selesnow** [comment]
Так же обсуждение проблемы было на Facebook, доступно по [ссылке](https://m.facebook.com/groups/1385177031811951?view=permalink&id=1990876954575286), может там найдёте ответ.

**Comment by egkasatkin** [comment]
Алексей, Такая же проблема с бесконечно загрузкой.



setwd("C:\\Users\\e.kasatkin\\Documents\\R\\win-library\\3.6")
library(ryandexdirect, lib.loc = "C:\\Users\\e.kasatkin\\Documents\\R\\win-library\\3.6")

# авторизация под агентским аккаунтом
yadirAuth(Login = "***", TokenPath = "C:\\Users\\e.kasatkin\\Documents\\R\\win-library\\3.6")

# список клиентов из агентского аккаунта
clientList <- yadirGetClientList(AgencyAccount = "***")

# загрузка статистики из рекламных аккаунтов привязанных к агентскому аккаунту
stat <- yadirGetReport(ReportType = "ACCOUNT_PERFORMANCE_REPORT", 
                       DateRangeType = "THIS_MONTH", 
                       FieldNames = c("Date",
                                      "Impressions",
                                      "Clicks",
                                      "Cost"), 
                       AgencyAccount = "***",
                       Login = clientList$Login)



если брать код до загрузки статистики, то все отлично работает, но со статистикой увы нет(
есть какие-нибудь мысли?
