### ISSUE TITLE
В HTTP-заголовке Client-Login указан несуществующий логин

### ISSUE THREAD

**Issue by nexter83** [selesnow/ryandexdirect#8]
Привет.  на линукс встала версия ryandexdirect_3.0.6.1  на винде встала ryandexdirect_3.0.4
на винде все ок работает а на линуксе пишет 
Error Code: 8800
Error Message: Объект не найден
Error Detail: В HTTP-заголовке Client-Login указан несуществующий логин

**Comment by selesnow** [comment]
Привет, а ты логин и токен один и тот же на винде и на линухе передал?
По идее на линухе токен не соответсвует логину

**Comment by nexter83** [comment]
да теперь все гуд стало
