### ISSUE TITLE
Ошибка при установке пакета ryandexdirect

### ISSUE THREAD

**Issue by AndreyTula** [selesnow/ryandexdirect#9]
Здравсвуйте! При выполнении команды install_github('selesnow/ryandexdirect')
получаю ошибку: 
Error in install_github("selesnow/ryandexdirect") : 
  could not find function "install_github"

Подскажите, пожалуйста, в чем может быть причина. Спасибо!

**Comment by selesnow** [comment]
Добрый день, изначально вам надо установить и подключить пакет `devtools`.

```r
install.packages("devtools")
library(devtools)
install_github("selesnow/ryandexdirect")
```

**Comment by AndreyTula** [comment]
Большак спасибо! Попробую.

пт, 31 авг. 2018 г. в 17:19, Alexey Seleznev <notifications@github.com>:

**Comment by AndreyTula** [comment]
Да, все получилось. Спасибо!

вс, 2 сент. 2018 г. в 22:25, Alexey Seleznev <notifications@github.com>:

**Comment by selesnow** [comment]
Добрый, повторно открываю тикет.

В вашем случае проблема в том, что имя пользователя Wndows заданно кириллицей "Олег", и библиотека, в которую устанавливаются пакеты находится вот тут C:/Users/Олег/Documents/R/win-library/3.5/, а кирилица в пути к библиотеке не допускается.

**Как решить проблему.**
1. Самый простой вариант просто изменить имя пользователя Олег на Oleg.
2. Более сложный, перенести библиотеку в другое место, так что в пути к ней было папок в названии которых есть кириллица, как это сделать можно узнать вот [тут](https://alexeyseleznev.wordpress.com/2018/08/08/%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5-r-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2-%D0%BD%D0%B0-windows-%D0%BE%D1%88%D0%B8/).

Если всё получится прошу закрыть тикет.

**Comment by Oleg-levwa** [comment]
Добрый день! Помог первый способ - изменение имени папки пользователя на латиницу. Спасибо за помощь!

**Comment by Oleg-levwa** [comment]
Тикет создавался не мной. К сожалению, не могу найти, где закрывается тикет.

**Comment by selesnow** [comment]
@JuliaDoshlova 

Добрый день Юлия!

Вы пытаетесь установить пакет с помощью стандартной команды `install.packages("ryandexdirect")`, данная команда устанавливает пакеты из основного репозитория CRAN, дело в том, что в этом репозитории пока не опубликован пакет `ryandexdirect`. Но на днях надеюсь он там появится.

**Как сейчас можно установить пакет**, воспользуйтесь приёмом описанном в README пакета, т.е. используйте пакет `devtools` и следующий код `install_github('selesnow/ryandexdirect')`

**Comment by Julia-Romanchuk** [comment]
Добрый день, при попытке установить Git с помощью sudo apt install git, возникает следующая ошибка: 
<pre>Чтение информации о состоянии… Готово
Некоторые пакеты не могут быть установлены. Возможно, то, что вы просите,
неосуществимо, или же вы используете нестабильную версию дистрибутива, где
запрошенные вами пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, вам поможет:

Следующие пакеты имеют неудовлетворённые зависимости:
 git : Зависит: libpcre2-8-0 (&gt;= 10.31) но он не может быть установлен
       Зависит: liberror-perl но он не может быть установлен
</pre>

 Подскажите, пожалуйста, в чем может быть причина. Спасибо!
